language: php

php:
  - 5.6

sudo: false

install:
  - travis_retry composer install --no-interaction --no-scripts --prefer-source

script:
  - touch storage/database.sqlite
  - php artisan migrate:install
  - php artisan migrate:refresh --seed --force
  - vendor/bin/codecept run;
  - vendor/bin/codecept run --coverage --coverage-xml;

before_install:
  - pip install --user codecov
after_success:
  - codecov